TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Shel.NeosBase': true

    userInterface:
      translation:
        autoInclude:
          'Shel.NeosBase': ['NodeTypes/*']

Shel:
  NeosBase:
    debug:
      liveReload:
        enabled: false
